services:
  - type: web
    name: tenderai-backend
    env: docker
    region: frankfurt # You can change this to a region closer to you
    plan: free
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tenderai-db
          property: connectionString
      # Any other secrets like JWT_SECRET can be added here
      # - key: JWT_SECRET
      #   generateValue: true



databases:
  - name: tenderai-db
    region: frankfurt
    plan: free
    databaseName: tenderai
    user: tenderai_user
